<?php

namespace Modules\Administrator\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Common\Models\Village;
use Modules\Core\Models\User;
use Modules\Volunteers\Models\Member;

class MemberTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $members = [
            [
                'name' => 'Ahmad Fauzi',
                'email' => 'fauzi@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-01-01',
                'phone' => '081234567890',
                'address' => 'Jl. Melati No. 10',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Siti Rahma',
                'email' => 'rahma@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-05-05',
                'phone' => '081345678901',
                'address' => 'Jl. Mawar No. 20',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bambang Sutrisno',
                'email' => 'bambang@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-03-12',
                'phone' => '081223344556',
                'address' => 'Jl. Jambu No. 15',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dewi Andini',
                'email' => 'dewi@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-06-18',
                'phone' => '081322211100',
                'address' => 'Jl. Mangga No. 32',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rizky Maulana',
                'email' => 'rizky@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1998-09-05',
                'phone' => '081322222222',
                'address' => 'Jl. Rambutan No. 25',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ayu Lestari',
                'email' => 'ayu@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-11-23',
                'phone' => '081311122233',
                'address' => 'Jl. Durian No. 40',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Fajar Pratama',
                'email' => 'fajar@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-08-15',
                'phone' => '081312345678',
                'address' => 'Jl. Sirsak No. 18',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ratna Sari',
                'email' => 'ratna@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-04-27',
                'phone' => '081322334455',
                'address' => 'Jl. Alpukat No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Adi Prasetyo',
                'email' => 'adi@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-12-10',
                'phone' => '081312334455',
                'address' => 'Jl. Nangka No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Indah Permata',
                'email' => 'indah@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-05-16',
                'phone' => '081323344556',
                'address' => 'Jl. Apel No. 8',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Taufik Hidayat',
                'email' => 'taufik@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-03-21',
                'phone' => '081324455667',
                'address' => 'Jl. Pisang No. 20',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Putri Amelia',
                'email' => 'putri@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-02-02',
                'phone' => '081322123456',
                'address' => 'Jl. Jeruk No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            // Tambahkan hingga 20 data sesuai pola ini

            [
                'name' => 'Agus Santoso',
                'email' => 'agus@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1980-07-12',
                'phone' => '081234567891',
                'address' => 'Jl. Anggrek No. 15',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Nurul Aini',
                'email' => 'nurul@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1997-03-10',
                'phone' => '081323456789',
                'address' => 'Jl. Kenanga No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rian Permadi',
                'email' => 'rian@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-12-01',
                'phone' => '081311122244',
                'address' => 'Jl. Mawar Putih No. 18',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Yuni Kartika',
                'email' => 'yuni@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-06-15',
                'phone' => '081322233344',
                'address' => 'Jl. Cempaka No. 20',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-04-25',
                'phone' => '081311144455',
                'address' => 'Jl. Melur No. 22',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Lina Febriani',
                'email' => 'lina@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-11-19',
                'phone' => '081322344556',
                'address' => 'Jl. Tanjung No. 13',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Fikri Alamsyah',
                'email' => 'fikri@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-01-29',
                'phone' => '081312344556',
                'address' => 'Jl. Dahlia No. 30',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rosa Indriani',
                'email' => 'rosa@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-08-11',
                'phone' => '081324567890',
                'address' => 'Jl. Flamboyan No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Eko Setiawan',
                'email' => 'eko@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-07-20',
                'phone' => '081311144466',
                'address' => 'Jl. Angsana No. 10',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rani Oktaviani',
                'email' => 'rani@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-09-02',
                'phone' => '081322123334',
                'address' => 'Jl. Kamboja No. 25',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Arif Setiawan',
                'email' => 'arif@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1986-02-14',
                'phone' => '081321123456',
                'address' => 'Jl. Sawo No. 8',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dwi Rahayu',
                'email' => 'dwi@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-03-06',
                'phone' => '081323344567',
                'address' => 'Jl. Salak No. 3',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bagus Priyanto',
                'email' => 'bagus@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-07-19',
                'phone' => '081311234567',
                'address' => 'Jl. Durian No. 40',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Maya Sari',
                'email' => 'maya@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-11-23',
                'phone' => '081322334567',
                'address' => 'Jl. Anggur No. 2',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],

            [
                'name' => 'Adi Saputra',
                'email' => 'adi.saputra@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-01-05',
                'phone' => '081234567891',
                'address' => 'Jl. Anggrek No. 14',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Indah Permata',
                'email' => 'indah.permata@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-03-15',
                'phone' => '081324567892',
                'address' => 'Jl. Melati No. 21',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bayu Anggara',
                'email' => 'bayu.anggara@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-05-21',
                'phone' => '081311223344',
                'address' => 'Jl. Mawar Putih No. 30',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ayu Kartika',
                'email' => 'ayu.kartika@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-06-20',
                'phone' => '081322334455',
                'address' => 'Jl. Flamboyan No. 7',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rizky Firmansyah',
                'email' => 'rizky.firmansyah@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-08-19',
                'phone' => '081311445566',
                'address' => 'Jl. Cempaka No. 18',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dewi Anggraini',
                'email' => 'dewi.anggraini@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-02-10',
                'phone' => '081324567893',
                'address' => 'Jl. Angsana No. 11',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Taufik Hidayat',
                'email' => 'taufik.hidayat@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-09-14',
                'phone' => '081312223344',
                'address' => 'Jl. Melur No. 22',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Putri Amelia',
                'email' => 'putri.amelia@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-07-05',
                'phone' => '081322334456',
                'address' => 'Jl. Dahlia No. 35',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Faisal Akbar',
                'email' => 'faisal.akbar@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-10-25',
                'phone' => '081311667788',
                'address' => 'Jl. Tanjung No. 29',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Siti Aisyah',
                'email' => 'siti.aisyah@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-11-11',
                'phone' => '081323334445',
                'address' => 'Jl. Sawo No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            // Total data = 10 (sisa data lainnya dipecah agar tidak terlalu panjang)

            [
                'name' => 'Agus Pratama',
                'email' => 'agus.pratama@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-04-15',
                'phone' => '081311889900',
                'address' => 'Jl. Pandan No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Lisa Kartika',
                'email' => 'lisa.kartika@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-03-08',
                'phone' => '081324556677',
                'address' => 'Jl. Jambu No. 4',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-05-09',
                'phone' => '081322667788',
                'address' => 'Jl. Kenanga No. 7',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ratna Dewi',
                'email' => 'ratna.dewi@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-12-01',
                'phone' => '081323445566',
                'address' => 'Jl. Cendana No. 14',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1986-07-30',
                'phone' => '081311998877',
                'address' => 'Jl. Angsana No. 16',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Nina Lestari',
                'email' => 'nina.lestari@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-09-25',
                'phone' => '081324889900',
                'address' => 'Jl. Cemara No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Andi Susilo',
                'email' => 'andi.susilo@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-06-18',
                'phone' => '081322556677',
                'address' => 'Jl. Merpati No. 8',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Maria Angelica',
                'email' => 'maria.angelica@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1997-01-22',
                'phone' => '081325667788',
                'address' => 'Jl. Mawar No. 20',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rahmat Hidayat',
                'email' => 'rahmat.hidayat@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-11-12',
                'phone' => '081311445566',
                'address' => 'Jl. Tanjung No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Yuli Astuti',
                'email' => 'yuli.astuti@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-03-30',
                'phone' => '081322334457',
                'address' => 'Jl. Flamboyan No. 3',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Fahmi Alamsyah',
                'email' => 'fahmi.alamsyah@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-08-19',
                'phone' => '081311223345',
                'address' => 'Jl. Anggrek No. 2',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],

            [
                'name' => 'Joko Hartono',
                'email' => 'joko.hartono@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-02-14',
                'phone' => '081311665544',
                'address' => 'Jl. Palem No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sari Dewi',
                'email' => 'sari.dewi@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-11-11',
                'phone' => '081324778899',
                'address' => 'Jl. Mahoni No. 15',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Teguh Wibowo',
                'email' => 'teguh.wibowo@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-07-23',
                'phone' => '081322998877',
                'address' => 'Jl. Kamboja No. 11',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Anita Larasati',
                'email' => 'anita.larasati@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-09-19',
                'phone' => '081325557788',
                'address' => 'Jl. Mangga No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bayu Saputra',
                'email' => 'bayu.saputra@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-03-06',
                'phone' => '081311778899',
                'address' => 'Jl. Salak No. 17',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Mila Kartini',
                'email' => 'mila.kartini@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-04-12',
                'phone' => '081324445566',
                'address' => 'Jl. Anggrek No. 21',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dian Permadi',
                'email' => 'dian.permadi@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-12-25',
                'phone' => '081322667788',
                'address' => 'Jl. Sawo No. 18',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Intan Sari',
                'email' => 'intan.sari@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-01-05',
                'phone' => '081325334455',
                'address' => 'Jl. Belimbing No. 2',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rudi Hidayat',
                'email' => 'rudi.hidayat@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1986-05-22',
                'phone' => '081311112233',
                'address' => 'Jl. Durian No. 13',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sinta Lestari',
                'email' => 'sinta.lestari@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-06-10',
                'phone' => '081322223344',
                'address' => 'Jl. Rambutan No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],

            [
                'name' => 'Yusuf Pratama',
                'email' => 'yusuf.pratama@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-08-15',
                'phone' => '081399001122',
                'address' => 'Jl. Cemara No. 4',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Lestari Ayu',
                'email' => 'lestari.ayu@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1997-03-25',
                'phone' => '081300112233',
                'address' => 'Jl. Pinus No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bambang Saputra',
                'email' => 'bambang.saputra@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-07-19',
                'phone' => '081377889900',
                'address' => 'Jl. Jati No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rina Mardiana',
                'email' => 'rina.mardiana@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-09-30',
                'phone' => '081344556677',
                'address' => 'Jl. Bambu No. 11',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Adi Kurniawan',
                'email' => 'adi.kurniawan@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-10-22',
                'phone' => '081322334455',
                'address' => 'Jl. Angsana No. 3',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Siti Khadijah',
                'email' => 'siti.khadijah@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-01-11',
                'phone' => '081344556688',
                'address' => 'Jl. Randu No. 8',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-05-18',
                'phone' => '081300445566',
                'address' => 'Jl. Flamboyan No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Lila Anjani',
                'email' => 'lila.anjani@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-04-05',
                'phone' => '081311223344',
                'address' => 'Jl. Kelapa No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Agus Santoso',
                'email' => 'agus.santoso@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-12-12',
                'phone' => '081399112233',
                'address' => 'Jl. Cendana No. 7',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dewi Anggraini',
                'email' => 'dewi.anggraini@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-06-16',
                'phone' => '081322556677',
                'address' => 'Jl. Sengon No. 1',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Rudi Setiawan',
                'email' => 'rudi.setiawan@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-02-14',
                'phone' => '081355667788',
                'address' => 'Jl. Meranti No. 2',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Wati Nurhayati',
                'email' => 'wati.nurhayati@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-11-09',
                'phone' => '081388776655',
                'address' => 'Jl. Jambu No. 3',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Krisna Adi',
                'email' => 'krisna.adi@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1989-07-22',
                'phone' => '081377889911',
                'address' => 'Jl. Kenanga No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sari Puspitasari',
                'email' => 'sari.puspitasari@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-05-17',
                'phone' => '081311667788',
                'address' => 'Jl. Salak No. 4',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Budi Haryanto',
                'email' => 'budi.haryanto@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-10-11',
                'phone' => '081322778899',
                'address' => 'Jl. Kantil No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Maya Putri',
                'email' => 'maya.putri@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-04-21',
                'phone' => '081366778899',
                'address' => 'Jl. Kelapa Gading No. 7',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ibrahim Malik',
                'email' => 'ibrahim.malik@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-09-18',
                'phone' => '081377665544',
                'address' => 'Jl. Mawar No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dini Amalia',
                'email' => 'dini.amalia@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-06-30',
                'phone' => '081299887766',
                'address' => 'Jl. Pahlawan No. 11',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Eko Purnomo',
                'email' => 'eko.purnomo@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-03-14',
                'phone' => '081388776633',
                'address' => 'Jl. Cempaka No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Intan Sari',
                'email' => 'intan.sari@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1997-02-05',
                'phone' => '081344556622',
                'address' => 'Jl. Sumber No. 13',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Carlos Silva',
                'email' => 'carlos.silva@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1984-01-22',
                'phone' => '081288776655',
                'address' => 'Rua das Palmeiras No. 4',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ana Costa',
                'email' => 'ana.costa@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-03-13',
                'phone' => '081277889900',
                'address' => 'Av. Rio Branco No. 6',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'José Almeida',
                'email' => 'jose.almeida@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-09-02',
                'phone' => '081299887766',
                'address' => 'Rua da Liberdade No. 7',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Maria Oliveira',
                'email' => 'maria.oliveira@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-11-10',
                'phone' => '081311223344',
                'address' => 'Avenida São João No. 8',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Lucas Pereira',
                'email' => 'lucas.pereira@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1995-05-18',
                'phone' => '081399887755',
                'address' => 'Rua do Sol No. 9',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Fernanda Santos',
                'email' => 'fernanda.santos@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-07-25',
                'phone' => '081366778899',
                'address' => 'Rua do Cruzeiro No. 10',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ricardo Lima',
                'email' => 'ricardo.lima@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-12-30',
                'phone' => '081322223344',
                'address' => 'Rua da Paz No. 11',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Giovanna Rocha',
                'email' => 'giovanna.rocha@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-06-12',
                'phone' => '081355667788',
                'address' => 'Avenida Paulista No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Bruno Souza',
                'email' => 'bruno.souza@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-02-28',
                'phone' => '081388889900',
                'address' => 'Rua das Flores No. 13',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Juliana Costa',
                'email' => 'juliana.costa@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1997-01-05',
                'phone' => '081277889922',
                'address' => 'Avenida Rio No. 14',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Nikos Papadopoulos',
                'email' => 'nikos.papadopoulos@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-07-11',
                'phone' => '081234567890',
                'address' => 'Egnatia St No. 15',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Maria Antoniou',
                'email' => 'maria.antoniou@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-05-22',
                'phone' => '081277889901',
                'address' => 'Athenes No. 10',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Alexandros Kotsis',
                'email' => 'alexandros.kotsis@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1992-09-08',
                'phone' => '081299887765',
                'address' => 'Lysikratous St No. 17',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sophia Nikolaou',
                'email' => 'sophia.nikolaou@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1988-02-15',
                'phone' => '081366778900',
                'address' => 'Corinthos No. 12',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Ioannis Christodoulou',
                'email' => 'ioannis.christodoulou@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1993-03-29',
                'phone' => '081377889922',
                'address' => 'Kifisias St No. 20',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Eleni Papageorgiou',
                'email' => 'eleni.papageorgiou@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1994-10-30',
                'phone' => '081288776643',
                'address' => 'Fokionos No. 21',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Dimitrios Stavrou',
                'email' => 'dimitrios.stavrou@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1987-11-19',
                'phone' => '081344556677',
                'address' => 'Panepistimiou St No. 23',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Katerina Georgiou',
                'email' => 'katerina.georgiou@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1991-12-05',
                'phone' => '081277889933',
                'address' => 'Evripidou St No. 25',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Vasilis Markou',
                'email' => 'vasilis.markou@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1996-01-11',
                'phone' => '081299887788',
                'address' => 'Othonos No. 26',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Stavros Pappas',
                'email' => 'stavros.pappas@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-04-14',
                'phone' => '081322223344',
                'address' => 'Mavromata St No. 28',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Joko Prasetyo',
                'email' => 'joko.prasetyo@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1985-06-15',
                'phone' => '081234567890',
                'address' => 'Jl. Raya Ngawi No. 5',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sri Wahyuni',
                'email' => 'sri.wahyuni@app.com',
                'gender' => 'Wanita',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1990-11-11',
                'phone' => '081276543210',
                'address' => 'Jl. Sumber Rejo No. 10',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
            [
                'name' => 'Sukardi Hartono',
                'email' => 'sukardi.hartono@app.com',
                'gender' => 'Pria',
                'place_of_birth' => 'Surakarta',
                'date_of_birth' => '1982-03-20',
                'phone' => '081298765432',
                'address' => 'Jl. Ngawi No. 15',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => '337201',
                'village_id' => Village::where('district_id', 337201)->inRandomOrder()->first()->id,
                'identity_number' => '337201' . str_pad(rand(0, 9999999999), 10, '0', STR_PAD_LEFT),
            ],
        ];

        foreach ($members as $member) {
            // Generate member number
            $lastMember = DB::table('members')
                ->orderBy('member_serial', 'desc')
                ->first();

            $lastSerial = $lastMember ? $lastMember->member_serial : null;

            $memberNumberData = Member::generateMemberNumber($lastSerial, $member['regency_id']);

            $avatar = 'images/users/user-' . rand(1, 11) . '.jpg';

            $admin = User::where('name', 'admin')->get()->first();

            // Insert member
            DB::table('members')->insert([
                'id' => Member::generateId(),
                'member_number' => $memberNumberData['member_number'],
                'member_code' => $memberNumberData['member_code'],
                'member_serial' => $memberNumberData['member_serial'],
                'name' => $member['name'],
                'gender' => $member['gender'],
                'place_of_birth' => $member['place_of_birth'],
                'date_of_birth' => $member['date_of_birth'],
                'phone' => $member['phone'],
                'email' => $member['email'],
                'address' => $member['address'],
                'province_id' => $member['province_id'],
                'regency_id' => $member['regency_id'],
                'district_id' => $member['district_id'],
                'village_id' => $member['village_id'],
                'identity_number' => $member['identity_number'],
                'status' => 'active',
                'verified_at' => now(),
                'verified_by' => $admin->id,
                'avatar' => $avatar,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
